#include "drone_settings.hpp"
#include "scanner.hpp"
#include "audio_alerts.hpp"
#include "drone_display.hpp"
#include "ui_receiver.hpp"
#include "file.hpp"
#include "file_path.hpp"

namespace drone_analyzer {

// ============================================================================
// DroneSettings Implementation
// ============================================================================

DroneSettings::DroneSettings() noexcept
    : scanning_mode(DEFAULT_SCANNING_MODE)
    , scan_interval_ms(SCAN_CYCLE_INTERVAL_MS)
    , scan_sensitivity(50)
    , spectrum_visible(true)
    , histogram_visible(true)
    , drone_list_visible(true)
    , status_bar_visible(true)
    , audio_alerts_enabled(false)
    , alert_rssi_threshold_dbm(RSSI_HIGH_THREAT_THRESHOLD_DBM)
    , min_threat_level(ThreatLevel::LOW) {
}

void DroneSettings::reset_to_defaults() noexcept {
    scanning_mode = DEFAULT_SCANNING_MODE;
    scan_interval_ms = SCAN_CYCLE_INTERVAL_MS;
    scan_sensitivity = 50;
    
    spectrum_visible = true;
    histogram_visible = true;
    drone_list_visible = true;
    status_bar_visible = true;
    
    audio_alerts_enabled = false;
    alert_rssi_threshold_dbm = RSSI_HIGH_THREAT_THRESHOLD_DBM;
    
    min_threat_level = ThreatLevel::LOW;
}

// ============================================================================
// DroneSettingsView Constructor / Destructor
// ============================================================================

DroneSettingsView::DroneSettingsView(NavigationView& nav, const ScanConfig& config, DroneScanner* scanner_ptr, DroneDisplay* display) noexcept
    : ui::View()
    , labels_({
        {{UI_POS_X(1), UI_POS_Y(3)}, "Scan Mode:", Theme::getInstance()->fg_light->foreground},
        {{UI_POS_X(1), UI_POS_Y(6)}, "Interval (ms):", Theme::getInstance()->fg_light->foreground},
        {{UI_POS_X(1), UI_POS_Y(9)}, "RSSI Threshold (dBm):", Theme::getInstance()->fg_light->foreground},
    })
    , field_scan_mode_({UI_POS_X(1), UI_POS_Y(4)}, 14, {
        {"Single", 0},
        {"Hopping", 1},
        {"Sequential", 2},
        {"Targeted", 3}
    })
    , field_scan_interval_({UI_POS_X(1), UI_POS_Y(7)}, 4, {10, 1000}, 10, ' ')
    , field_rssi_threshold_({UI_POS_X(1), UI_POS_Y(10)}, 4, {-90, -20}, 1, ' ')
    , check_audio_alerts_({UI_POS_X(1), UI_POS_Y(12)}, 15, "Audio Alerts", false)
    , check_spectrum_visible_({UI_POS_X(1), UI_POS_Y(14)}, 15, "Show Spectrum", false)
    , check_histogram_visible_({UI_POS_X(1), UI_POS_Y(16)}, 15, "Show Histogram", false)
    , button_defaults_({UI_POS_X(0), UI_POS_Y_BOTTOM(1), UI_POS_WIDTH(10), 28}, "DEFAULTS")
    , button_save_({UI_POS_X_CENTER(7), UI_POS_Y_BOTTOM(1), UI_POS_WIDTH(7), 28}, "SAVE")
    , button_cancel_({UI_POS_X_RIGHT(7), UI_POS_Y_BOTTOM(1), UI_POS_WIDTH(7), 28}, "CANCEL")
    , nav_(nav)
    , scanner_ptr_(scanner_ptr)
    , display_ptr_(display)
    , original_config_(config)
    , settings_()
    , settings_dirty_(false) {
    settings_.scanning_mode = config.mode;
    settings_.scan_interval_ms = config.scan_interval_ms;
    settings_.alert_rssi_threshold_dbm = config.rssi_threshold_dbm;

    add_children({
        &labels_,
        &field_scan_mode_,
        &field_scan_interval_,
        &field_rssi_threshold_,
        &check_audio_alerts_,
        &check_spectrum_visible_,
        &check_histogram_visible_,
        &button_defaults_,
        &button_save_,
        &button_cancel_
    });

    field_scan_mode_.set_by_value(static_cast<int32_t>(settings_.scanning_mode));
    field_scan_interval_.set_value(settings_.scan_interval_ms);
    field_rssi_threshold_.set_value(settings_.alert_rssi_threshold_dbm);
    check_audio_alerts_.set_value(settings_.audio_alerts_enabled);
    check_spectrum_visible_.set_value(settings_.spectrum_visible);
    check_histogram_visible_.set_value(settings_.histogram_visible);

    button_save_.on_select = [this](ui::Button&) {
        if (scanner_ptr_ != nullptr) {
            ScanConfig updated_config = original_config_;
            updated_config.mode = settings_.scanning_mode;
            updated_config.scan_interval_ms = settings_.scan_interval_ms;
            updated_config.rssi_threshold_dbm = settings_.alert_rssi_threshold_dbm;

            const ErrorCode err = scanner_ptr_->set_config(updated_config);
            if (err != ErrorCode::SUCCESS) {
                return;
            }
        }

        // Save settings to SD card file
        File file;
        const auto open_result = file.open(u"/ENHANCED_DRONE_ANALYZER_SETTINGS.TXT", false, true);
        if (open_result) {
            char buffer[256];
            size_t offset = 0;

            // Write header
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "# Enhanced Drone Analyzer Settings\n");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "# Auto-generated by EDA Settings\n\n");

            // Write scanning settings
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "spectrum_mode=%s\n",
                (settings_.scanning_mode == ScanningMode::SINGLE) ? "SINGLE" :
                (settings_.scanning_mode == ScanningMode::HOPPING) ? "HOPPING" :
                (settings_.scanning_mode == ScanningMode::SEQUENTIAL) ? "SEQUENTIAL" : "TARGETED");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "scan_interval_ms=%u\n", settings_.scan_interval_ms);
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "rssi_threshold_db=%d\n", settings_.alert_rssi_threshold_dbm);
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "enable_audio_alerts=%s\n", settings_.audio_alerts_enabled ? "true" : "false");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "show_spectrum=%s\n", settings_.spectrum_visible ? "true" : "false");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "show_histogram=%s\n", settings_.histogram_visible ? "true" : "false");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "freqman_path=DRONES\n");
            offset += snprintf(buffer + offset, sizeof(buffer) - offset,
                "settings_version=1.0\n");

            file.write(buffer, offset);
            file.close();
        }

        nav_.pop();
    };

    button_cancel_.on_select = [this](ui::Button&) {
        nav_.pop();
    };

    button_defaults_.on_select = [this](ui::Button&) {
        settings_.reset_to_defaults();
        settings_dirty_ = true;
        apply_settings();
    };

    field_scan_mode_.on_change = [this](size_t, int32_t v) {
        settings_.scanning_mode = static_cast<ScanningMode>(v);
        settings_dirty_ = true;
    };

    field_scan_interval_.on_change = [this](int32_t v) {
        settings_.scan_interval_ms = static_cast<uint32_t>(v);
        settings_dirty_ = true;
    };

    field_rssi_threshold_.on_change = [this](int32_t v) {
        settings_.alert_rssi_threshold_dbm = v;
        settings_dirty_ = true;
    };

    check_audio_alerts_.on_select = [this](ui::Checkbox&, bool v) {
        settings_.audio_alerts_enabled = v;
        AudioAlertManager::set_enabled(v);
        settings_dirty_ = true;
    };

    check_spectrum_visible_.on_select = [this](ui::Checkbox&, bool v) {
        settings_.spectrum_visible = v;
        if (display_ptr_ != nullptr) {
            display_ptr_->set_spectrum_visible(v);
        }
        settings_dirty_ = true;
    };

    check_histogram_visible_.on_select = [this](ui::Checkbox&, bool v) {
        settings_.histogram_visible = v;
        if (display_ptr_ != nullptr) {
            display_ptr_->set_histogram_visible(v);
        }
        settings_dirty_ = true;
    };
}

DroneSettingsView::~DroneSettingsView() noexcept {
}

void DroneSettingsView::paint(ui::Painter& painter) {
    (void)painter;
}

void DroneSettingsView::focus() {
    field_scan_mode_.focus();
}

void DroneSettingsView::reset_settings() noexcept {
    settings_.reset_to_defaults();
    settings_dirty_ = true;
    apply_settings();
}

ErrorCode DroneSettingsView::validate_settings() const noexcept {
    if (settings_.scanning_mode > ScanningMode::TARGETED) {
        return ErrorCode::INVALID_PARAMETER;
    }
    
    if (settings_.scan_interval_ms < 10 || settings_.scan_interval_ms > 1000) {
        return ErrorCode::INVALID_PARAMETER;
    }
    
    if (settings_.scan_sensitivity > 100) {
        return ErrorCode::INVALID_PARAMETER;
    }
    
    if (settings_.alert_rssi_threshold_dbm < RSSI_MIN_DBM ||
        settings_.alert_rssi_threshold_dbm > RSSI_MAX_DBM) {
        return ErrorCode::INVALID_PARAMETER;
    }
    
    if (settings_.min_threat_level > ThreatLevel::CRITICAL) {
        return ErrorCode::INVALID_PARAMETER;
    }
    
    return ErrorCode::SUCCESS;
}

void DroneSettingsView::apply_settings() noexcept {
    field_scan_mode_.set_by_value(static_cast<int32_t>(settings_.scanning_mode));
    field_scan_interval_.set_value(settings_.scan_interval_ms);
    field_rssi_threshold_.set_value(settings_.alert_rssi_threshold_dbm);
    check_audio_alerts_.set_value(settings_.audio_alerts_enabled);
    check_spectrum_visible_.set_value(settings_.spectrum_visible);
    check_histogram_visible_.set_value(settings_.histogram_visible);
}

} // namespace drone_analyzer
