#include <cstdint>
#include <cstring>

#include "drone_sweep_view.hpp"
#include "scanner.hpp"
#include "constants.hpp"
#include "ui_receiver.hpp"
#include "file.hpp"
#include "file_path.hpp"

namespace drone_analyzer {

DroneSweepView::DroneSweepView(NavigationView& nav, const ScanConfig& config, DroneScanner* scanner_ptr) noexcept
    : ui::View()
    , nav_(nav)
    , scanner_ptr_(scanner_ptr)
    , original_config_(config) {
    add_children({
        &labels_sw1_,
        &field_sw1_start_,
        &field_sw1_end_,
        &field_sw1_step_,
        &labels_sw2_,
        &check_sw2_enabled_,
        &field_sw2_start_,
        &field_sw2_end_,
        &field_sw2_step_,
        &button_defaults_,
        &button_save_,
    });

    // Populate from config
    field_sw1_start_.set_value(static_cast<int32_t>(config.sweep_start_freq / 1000000ULL));
    field_sw1_end_.set_value(static_cast<int32_t>(config.sweep_end_freq / 1000000ULL));
    field_sw1_step_.set_value(static_cast<int32_t>(config.sweep_step_freq / 1000ULL));

    check_sw2_enabled_.set_value(config.sweep2_enabled);
    field_sw2_start_.set_value(static_cast<int32_t>(config.sweep2_start_freq / 1000000ULL));
    field_sw2_end_.set_value(static_cast<int32_t>(config.sweep2_end_freq / 1000000ULL));
    field_sw2_step_.set_value(static_cast<int32_t>(config.sweep2_step_freq / 1000ULL));

    button_save_.on_select = [this](ui::Button&) {
        save_settings();
        nav_.pop();
    };

    button_defaults_.on_select = [this](ui::Button&) {
        apply_defaults();
    };
}

DroneSweepView::~DroneSweepView() noexcept {
}

void DroneSweepView::focus() {
    field_sw1_start_.focus();
}

void DroneSweepView::save_settings() noexcept {
    // Read values from UI
    FreqHz sw1_start = static_cast<FreqHz>(field_sw1_start_.value()) * 1000000ULL;
    FreqHz sw1_end = static_cast<FreqHz>(field_sw1_end_.value()) * 1000000ULL;
    FreqHz sw1_step = static_cast<FreqHz>(field_sw1_step_.value()) * 1000ULL;

    bool sw2_enabled = check_sw2_enabled_.value();
    FreqHz sw2_start = static_cast<FreqHz>(field_sw2_start_.value()) * 1000000ULL;
    FreqHz sw2_end = static_cast<FreqHz>(field_sw2_end_.value()) * 1000000ULL;
    FreqHz sw2_step = static_cast<FreqHz>(field_sw2_step_.value()) * 1000ULL;

    // Validate: start must be < end
    if (sw1_start >= sw1_end) {
        sw1_end = sw1_start + 20000000;
    }
    if (sw2_enabled && sw2_start >= sw2_end) {
        sw2_end = sw2_start + 20000000;
    }

    // Update scanner config
    if (scanner_ptr_ != nullptr) {
        ScanConfig updated_config = original_config_;
        updated_config.sweep_start_freq = sw1_start;
        updated_config.sweep_end_freq = sw1_end;
        updated_config.sweep_step_freq = sw1_step;
        updated_config.sweep2_start_freq = sw2_start;
        updated_config.sweep2_end_freq = sw2_end;
        updated_config.sweep2_step_freq = sw2_step;
        updated_config.sweep2_enabled = sw2_enabled;
        (void)scanner_ptr_->set_config(updated_config);
    }

    // Read existing file, update sweep keys, write back
    File file;
    ensure_directory(settings_dir);

    // Read existing file content into static buffer
    static char file_buf[2048];
    size_t file_len = 0;
    const auto open_result = file.open(settings_dir / u"eda_settings.txt", true, false);
    if (!open_result) {
        // File exists, read it
        constexpr size_t CHUNK = 256;
        uint8_t chunk[CHUNK];
        while (true) {
            const auto read_result = file.read(chunk, CHUNK);
            if (!read_result.is_ok() || read_result.value() == 0) break;
            const size_t bytes = read_result.value();
            for (size_t i = 0; i < bytes && file_len < sizeof(file_buf) - 1; ++i) {
                file_buf[file_len++] = static_cast<char>(chunk[i]);
            }
        }
        file.close();
    }
    file_buf[file_len] = '\0';

    // Create/overwrite file for writing
    const auto create_result = file.create(settings_dir / u"eda_settings.txt");
    if (create_result) return;

    // Write output: non-sweep lines from existing file, plus sweep keys
    static char out_buf[2048];
    size_t out_offset = 0;

    // If file didn't exist, write defaults for non-sweep settings
    if (file_len == 0) {
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "# Enhanced Drone Analyzer Settings\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "# Auto-generated by EDA\n\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_mode=SEQUENTIAL\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "scan_interval_ms=%lu\n", (unsigned long)SCAN_CYCLE_INTERVAL_MS);
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "sensitivity=70\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "rssi_threshold_db=%ld\n", (long)RSSI_DETECTION_THRESHOLD_DBM);
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "enable_audio_alerts=true\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "volume=70\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "show_spectrum=true\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "show_histogram=true\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_detection=false\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_margin=15\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_min_width=1\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_max_width=100\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "spectrum_peak_sharpness=50\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "dwell_enabled=false\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "confirm_count_enabled=false\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "noise_blacklist_enabled=false\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "median_enabled=false\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "freqman_path=DRONES\n");
        out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
            "settings_version=1.0\n");
    } else {
        // Parse existing file and copy non-sweep lines
        size_t line_start = 0;
        for (size_t i = 0; i <= file_len; ++i) {
            if (i == file_len || file_buf[i] == '\n' || file_buf[i] == '\r') {
                if (i > line_start) {
                    // Check if this is a sweep line to skip
                    bool is_sweep_line = false;
                    const char* sweep_keys[] = {
                        "sweep_start_mhz=", "sweep_end_mhz=", "sweep_step_khz=",
                        "sweep2_start_mhz=", "sweep2_end_mhz=", "sweep2_step_khz=",
                        "sweep2_enabled=",
                    };
                    for (const auto& key : sweep_keys) {
                        const size_t klen = __builtin_strlen(key);
                        if ((i - line_start) >= klen &&
                            __builtin_memcmp(file_buf + line_start, key, klen) == 0) {
                            is_sweep_line = true;
                            break;
                        }
                    }
                    if (!is_sweep_line && (i - line_start) > 0) {
                        const size_t copy_len = i - line_start;
                        if (out_offset + copy_len + 1 < sizeof(out_buf)) {
                            __builtin_memcpy(out_buf + out_offset, file_buf + line_start, copy_len);
                            out_offset += copy_len;
                            out_buf[out_offset++] = '\n';
                        }
                    }
                }
                // Skip \r\n pairs
                if (i < file_len && file_buf[i] == '\r' && (i + 1) < file_len && file_buf[i + 1] == '\n') {
                    i++;
                }
                line_start = i + 1;
            }
        }
    }

    // Append sweep keys
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep_start_mhz=%lu\n", (unsigned long)(sw1_start / 1000000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep_end_mhz=%lu\n", (unsigned long)(sw1_end / 1000000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep_step_khz=%lu\n", (unsigned long)(sw1_step / 1000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep2_start_mhz=%lu\n", (unsigned long)(sw2_start / 1000000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep2_end_mhz=%lu\n", (unsigned long)(sw2_end / 1000000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep2_step_khz=%lu\n", (unsigned long)(sw2_step / 1000));
    out_offset += snprintf(out_buf + out_offset, sizeof(out_buf) - out_offset,
        "sweep2_enabled=%s\n", sw2_enabled ? "true" : "false");

    file.write(out_buf, out_offset);
    file.close();
}

void DroneSweepView::apply_defaults() noexcept {
    field_sw1_start_.set_value(5700);
    field_sw1_end_.set_value(5900);
    field_sw1_step_.set_value(20000);
    check_sw2_enabled_.set_value(false);
    field_sw2_start_.set_value(2400);
    field_sw2_end_.set_value(2500);
    field_sw2_step_.set_value(20000);
}

} // namespace drone_analyzer
